x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "3"

services:
  api-aot:
    image: dotnet-benchmark/api-aot:v1.0.0
    container_name: api-aot-service

    build:
      context: ./Api.Aot
      dockerfile: Dockerfile
    ports:
      - "5555:8080"
    restart: always
    networks:
      - backend-net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          memory: 512M

  api-jit:
    image: dotnet-benchmark/api-jit:v1.0.0
    container_name: api-jit-service

    build:
      context: ./Api.Jit
      dockerfile: Dockerfile
    ports:
      - "6666:8080"
    restart: always
    networks:
      - backend-net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          memory: 512M

networks:
  backend-net:
    driver: bridge
