x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "3"

services:
  api-aot:
    image: dotnet-benchmark/api-aot:${IMAGE_TAG:-latest}
    container_name: api-aot-service
    logging: *default-logging
    
    build:
      context: ./Api.Aot
      dockerfile: Dockerfile
    ports:
      - "${API_AOT_PORT:-45555}:8080"
    restart: always
    networks:
      - backend-net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          memory: 512M

  api-jit:
    image: dotnet-benchmark/api-jit:${IMAGE_TAG:-latest}
    container_name: api-jit-service
    logging: *default-logging
    
    build:
      context: ./Api.Jit
      dockerfile: Dockerfile
    ports:
      - "${API_JIT_PORT:-46666}:8080"
    restart: always
    networks:
      - backend-net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          memory: 512M

networks:
  backend-net:
    driver: bridge
